# Generated by Django 3.2.6 on 2021-08-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210817_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='question', to='quiz.Quiz'),
        ),
    ]
