# Generated by Django 3.2.6 on 2021-08-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210817_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quiz', to='quiz.Question'),
        ),
    ]
