# Generated by Django 3.2.6 on 2021-08-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210817_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='all_answers',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.CharField(default='', max_length=255),
        ),
    ]
