# Generated by Django 3.2.6 on 2021-08-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='quiz.Question'),
        ),
    ]
