# Generated by Django 3.2.6 on 2021-08-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210818_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', to='quiz.Question'),
        ),
    ]
