# Generated by Django 3.2.6 on 2021-08-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_answer_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='vote',
        ),
    ]
