# Generated by Django 3.2.6 on 2021-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_answerstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerstatistics',
            name='right_answers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answerstatistics',
            name='wrong_answers',
            field=models.IntegerField(),
        ),
    ]
