# Generated by Django 3.2.6 on 2021-08-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20210820_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='right_answer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
