# Generated by Django 3.2.6 on 2021-08-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_answer_right_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='right_answer',
        ),
    ]
