# Generated by Django 3.2.6 on 2021-08-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_remove_answer_right_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passage_date',
            field=models.DateField(null=True),
        ),
    ]
