# Generated by Django 3.2.6 on 2021-08-21 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0020_quiz_passage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passage_user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
