# Generated by Django 3.2.6 on 2021-08-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_quiz_passage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='all_answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answers',
        ),
        migrations.DeleteModel(
            name='AnswerStatistics',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
