# Generated by Django 3.2.6 on 2021-08-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20210821_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='passage_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
